[build]
  # No build command needed for static HTML site
  command = ""
  # Publish the root directory since index.html is at the root
  publish = ""

# Ensure proper MIME types for assets
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml" 